{% set name = "edfio" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/edfio-{{ version }}.tar.gz
  sha256: 92b5919d5c9bb9cc8555da8c390f72fc5475ef0fc9007158fd7dffdb1257b0f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<4.0.0,<3.13
    - numpy >=1.22.0

test:
  imports:
    - edfio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/the-siesta-group/edfio
  summary: Read and write EDF/EDF+ files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hofaflo
